name: 'Setup Chryse'

inputs:
  install-oss-cad-suite:
    description: 'Install OSS CAD Suite.'
    required: false

  github-token:
    description: 'GitHub token used by YosysHQ/setup-oss-cad-suite.'
    required: false

runs:
  using: 'composite'
  steps:
  - name: Checkout Chryse
    uses: actions/checkout@v4
    with:
      repository: chryse-hdl/chryse

  - name: Set up JDK 22
    uses: actions/setup-java@v4
    with:
      java-version: '22'
      distribution: 'temurin'
      cache: 'sbt'

  - name: Install sbt
    run: |
      wget -q https://github.com/sbt/sbt/releases/download/v1.9.8/sbt-1.9.8.tgz
      tar xf sbt-1.9.8.tgz
      echo "$PWD/sbt/bin" >> $GITHUB_PATH
    shell: bash

  - name: Install Verilator
    if: ${{ ! inputs.install-oss-cad-suite }}
    run: sudo apt-get install -y verilator
    shell: bash

  - name: Build and install Chryse locally
    run: sbt publishLocal
    shell: bash

  - name: Install OSS CAD Suite
    if: ${{ inputs.install-oss-cad-suite }}
    uses: YosysHQ/setup-oss-cad-suite@v3
    with:
      github-token: ${{ inputs.github-token }}

  - name: Report Yosys version
    if: ${{ inputs.install-oss-cad-suite }}
    run: yosys --version
    shell: bash