name: Test action

on: [push]

jobs:
  test-default:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Chryse (use this repo)
        uses: ./.

      - name: Ensure sbt is found by calling action
        run: sbt --version

  test-source-refs:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Chryse and Athena (use this repo)
        uses: ./.
        with:
          source-ref: main
          athena-source-ref: main

      - name: Ensure sbt is found by calling action
        run: sbt --version

  test-zig:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Chryse with Zig (use this repo)
        uses: ./.
        with:
          install-zig: 0.13.0
