name: Test action

on: [push]

jobs:
  test-default:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Chryse (use this repo)
        uses: ./.

      - name: Ensure sbt is found by calling action
        run: sbt --version

  test-source-ref:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Chryse (use this repo)
        uses: ./.
        with:
          source-ref: main

      - name: Ensure sbt is found by calling action
        run: sbt --version
